In [1]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.shape

(3900, 18)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().values.any()

np.True_

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df[df.isnull().any(axis=1)]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
38,39,29,Male,Dress,Clothing,37,Florida,M,Red,Winter,NaN,Yes,2-Day Shipping,Yes,Yes,44,Venmo,Every 3 Months
50,51,49,Male,Blouse,Clothing,28,Maryland,M,Red,Spring,NaN,Yes,Store Pickup,Yes,Yes,39,Debit Card,Bi-Weekly
80,81,19,Male,Sandals,Footwear,72,New York,XL,Blue,Summer,NaN,Yes,Store Pickup,Yes,Yes,24,Credit Card,Every 3 Months
96,97,32,Male,Gloves,Accessories,73,Delaware,S,Gold,Spring,NaN,Yes,Express,Yes,Yes,43,Venmo,Every 3 Months
262,263,37,Male,Pants,Clothing,40,Hawaii,M,Teal,Summer,NaN,Yes,Next Day Air,Yes,Yes,6,Debit Card,Annually
330,331,46,Male,Sweater,Clothing,51,North Dakota,M,Beige,Winter,NaN,Yes,Express,Yes,Yes,43,Venmo,Bi-Weekly
356,357,56,Male,Pants,Clothing,80,Nevada,L,Black,Spring,NaN,Yes,Standard,Yes,Yes,27,Cash,Weekly
383,384,50,Male,Sunglasses,Accessories,77,West Virginia,S,Magenta,Fall,NaN,Yes,Standard,Yes,Yes,6,PayPal,Quarterly
419,420,53,Male,Shorts,Clothing,91,Utah,S,Teal,Winter,NaN,Yes,Free Shipping,Yes,Yes,14,Credit Card,Every 3 Months
442,443,29,Male,Sunglasses,Accessories,69,Michigan,M,Olive,Fall,NaN,Yes,Store Pickup,Yes,Yes,31,Credit Card,Quarterly
452,453,45,Male,Pants,Clothing,45,Missouri,M,Violet,Summer,NaN,Yes,Express,Yes,Yes,39,PayPal,Fortnightly
460,461,64,Male,Shoes,Footwear,65,South Carolina,L,Teal,Summer,NaN,Yes,Store Pickup,Yes,Yes,27,Bank Transfer,Weekly
491,492,49,Male,Coat,Outerwear,69,Vermont,M,Silver,Summer,NaN,Yes,2-Day Shipping,Yes,Yes,24,Credit Card,Bi-Weekly
512,513,19,Male,Gloves,Accessories,49,New York,L,Peach,Winter,NaN,Yes,Next Day Air,Yes,Yes,2,Bank Transfer,Monthly
560,561,25,Male,Jewelry,Accessories,48,Louisiana,L,Red,Fall,NaN,Yes,Free Shipping,Yes,Yes,12,Debit Card,Annually
628,629,69,Male,Sweater,Clothing,85,Massachusetts,M,White,Fall,NaN,Yes,2-Day Shipping,Yes,Yes,29,Credit Card,Monthly
799,800,55,Male,Belt,Accessories,55,Nevada,L,Brown,Summer,NaN,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
829,830,42,Male,Socks,Clothing,57,Idaho,S,Silver,Spring,NaN,Yes,2-Day Shipping,Yes,Yes,14,Credit Card,Fortnightly
861,862,46,Male,Skirt,Clothing,100,Virginia,XL,Green,Spring,NaN,Yes,2-Day Shipping,Yes,Yes,35,Credit Card,Every 3 Months
888,889,49,Male,Scarf,Accessories,77,New Hampshire,S,Gold,Spring,NaN,Yes,Express,Yes,Yes,44,Cash,Annually
1072,1073,48,Male,Shorts,Clothing,92,Idaho,L,Gold,Fall,NaN,No,Express,Yes,Yes,34,Debit Card,Fortnightly
1109,1110,66,Male,Hoodie,Clothing,97,Oklahoma,L,Violet,Winter,NaN,No,Next Day Air,Yes,Yes,2,Venmo,Weekly
1124,1125,42,Male,Sweater,Clothing,20,Iowa,M,Orange,Spring,NaN,No,Express,Yes,Yes,40,Cash,Quarterly
1134,1135,62,Male,T-shirt,Clothing,81,Wisconsin,M,Brown,Summer,NaN,No,Express,Yes,Yes,2,Venmo,Every 3 Months
1151,1152,41,Male,Blouse,Clothing,86,Ohio,M,Gray,Spring,NaN,No,Express,Yes,Yes,24,Credit Card,Weekly
1176,1177,36,Male,Dress,Clothing,83,Oregon,M,Red,Winter,NaN,No,Free Shipping,Yes,Yes,39,PayPal,Quarterly
1189,1190,64,Male,Shirt,Clothing,97,Arkansas,XL,Teal,Summer,NaN,No,Free Shipping,Yes,Yes,28,Debit Card,Annually
1208,1209,20,Male,Boots,Footwear,100,Wisconsin,S,Red,Winter,NaN,No,2-Day Shipping,Yes,Yes,8,Debit Card,Annually
1220,1221,67,Male,Gloves,Accessories,64,Kentucky,M,Green,Winter,NaN,No,Express,Yes,Yes,36,Bank Transfer,Quarterly
1230,1231,25,Male,Hat,Accessories,80,Illinois,L,Brown,Spring,NaN,No,Standard,Yes,Yes,49,Venmo,Monthly
1247,1248,65,Male,T-shirt,Clothing,99,Virginia,M,Charcoal,Spring,NaN,No,Express,Yes,Yes,18,Venmo,Bi-Weekly
1292,1293,26,Male,Belt,Accessories,61,Kentucky,M,Maroon,Summer,NaN,No,Free Shipping,Yes,Yes,42,Bank Transfer,Annually
1313,1314,70,Male,Shoes,Footwear,28,Missouri,M,Lavender,Summer,NaN,No,Free Shipping,Yes,Yes,23,Credit Card,Bi-Weekly
1326,1327,40,Male,Shoes,Footwear,50,Texas,M,Indigo,Spring,NaN,No,Free Shipping,Yes,Yes,17,Cash,Monthly
1334,1335,46,Male,Coat,Outerwear,52,West Virginia,S,White,Spring,NaN,No,Store Pickup,Yes,Yes,12,Venmo,Monthly
1341,1342,26,Male,Hoodie,Clothing,27,Rhode Island,XL,Yellow,Fall,NaN,No,Standard,Yes,Yes,31,Bank Transfer,Quarterly
1370,1371,27,Male,Scarf,Accessories,67,Montana,L,Peach,Summer,NaN,No,2-Day Shipping,Yes,Yes,41,Bank Transfer,Every 3 Months

In [10]:
df.groupby('Category').groups
df.groupby('Category').size()

for category, data in df.groupby('Category'):
    print(category)
    print(data)
    print("-===-===-===-============------=========")

Accessories
      Customer ID  Age  Gender Item Purchased     Category  \
9              10   57    Male        Handbag  Accessories
16             17   25    Male     Sunglasses  Accessories
26             27   38    Male        Jewelry  Accessories
28             29   54    Male        Handbag  Accessories
30             31   57    Male        Jewelry  Accessories
...           ...  ...     ...            ...          ...
3892         3893   35  Female        Jewelry  Accessories
3893         3894   21  Female            Hat  Accessories
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)        Location Size   Color  Season  \
9                        31        Missouri    M    Pink  Spring
16                       36         Alabama    S    Gray  Spring
26                       20          Nevada    M     Red  Spring
28                       94  North Carolina    M    Gray    Fall
30                       31  North Carolina    L   Black  Winter
...                     ...             ...  ...     ...     ...
3892                     86        Michigan    L  Indigo  Summer
3893                     64   Massachusetts    L   White    Fall
3896                     49            Iowa    L   White  Spring
3897                     33      New Jersey    L   Green  Spring
3899                     81      California    M   Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
9               4.8                 Yes  2-Day Shipping              Yes
16              4.1                 Yes    Next Day Air              Yes
26              3.6                 Yes    Next Day Air              Yes
28              4.4                 Yes   Free Shipping              Yes
30              4.7                 Yes        Standard              Yes
...             ...                 ...             ...              ...
3892            3.5                  No        Standard               No
3893            3.3                  No    Store Pickup               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
9                Yes                   4           Cash              Quarterly
16               Yes                  44     Debit Card              Bi-Weekly
26               Yes                  13    Credit Card               Annually
28               Yes                  41         PayPal         Every 3 Months
30               Yes                  16    Credit Card                Monthly
...              ...                 ...            ...                    ...
3892              No                   5         PayPal            Fortnightly
3893              No                  29  Bank Transfer              Bi-Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3899              No                  33          Venmo              Quarterly

[1240 rows x 18 columns]
-===-===-===-============------=========
Clothing
      Customer ID  Age  Gender Item Purchased  Category  \
0               1   55    Male         Blouse  Clothing
1               2   19    Male        Sweater  Clothing
2               3   50    Male          Jeans  Clothing
4               5   45    Male         Blouse  Clothing
6               7   63    Male          Shirt  Clothing
...           ...  ...     ...            ...       ...
3889         3890   57  Female          Dress  Clothing
3890         3891   35  Female          Shirt  Clothing
3891         3892   36  Female          Dress  Clothing
3894         3895   66  Female          Skirt  Clothing
3895         3896   40  Female         Hoodie  Clothing

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
6                        85        Montana    M       Gray    Fall
...                     ...            ...  ...        ...     ...
3889                     65         Alaska    S     Yellow  Spring
3890                     81       Nebraska   XL      Green  Winter
3891                     30       Colorado    L      Peach  Winter
3894                     78    Connecticut    L      White  Spring
3895                     28       Virginia    L  Turquoise  Summer

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
4               2.7                 Yes   Free Shipping              Yes
6               3.2                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3889            3.5                  No         Express               No
3890            2.6                  No        Standard               No
3891            4.7                  No   Free Shipping               No
3894            3.9                  No  2-Day Shipping               No
3895            4.2                  No  2-Day Shipping               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
4                Yes                  31         PayPal               Annually
6                Yes                  49           Cash              Quarterly
...              ...                 ...            ...                    ...
3889              No                  49  Bank Transfer               Annually
3890              No                  33     Debit Card               Annually
3891              No                   6  Bank Transfer              Quarterly
3894              No                  44    Credit Card         Every 3 Months
3895              No                  32          Venmo                 Weekly

[1737 rows x 18 columns]
-===-===-===-============------=========
Footwear
      Customer ID  Age  Gender Item Purchased  Category  \
3               4   21    Male        Sandals  Footwear
5               6   46    Male       Sneakers  Footwear
10             11   53    Male          Shoes  Footwear
62             63   30    Male       Sneakers  Footwear
64             65   65    Male          Boots  Footwear
...           ...  ...     ...            ...       ...
3873         3874   42  Female        Sandals  Footwear
3876         3877   60  Female          Shoes  Footwear
3884         3885   47  Female        Sandals  Footwear
3888         3889   45  Female       Sneakers  Footwear
3898         3899   44  Female          Shoes  Footwear

      Purchase Amount (USD)      Location Size    Color  Season  \
3                        90  Rhode Island    M   Maroon  Spring
5                        20       Wyoming    M    White  Summer
10                       34      Arkansas    L   Purple    Fall
62                       21   Mississippi    S  Magenta  Spring
64                       83       Alabama    S    Green    Fall
...                     ...           ...  ...      ...     ...
3873                     43     Louisiana    L   Silver  Summer
3876                     85     Wisconsin    S     Cyan    Fall
3884                     29      Maryland    M    Brown    Fall
3888                     69      Virginia    M   Violet  Spring
3898                     77     Minnesota    S    Brown  Summer

      Review Rating Subscription Status   Shipping Type Discount Applied  \
3               3.5                 Yes    Next Day Air              Yes
5               2.9                 Yes        Standard              Yes
10              4.1                 Yes    Store Pickup              Yes
62              3.8                 Yes   Free Shipping              Yes
64              4.8                 Yes        Standard              Yes
...             ...                 ...             ...              ...
3873            4.0                  No        Standard               No
3876            2.6                  No  2-Day Shipping               No
3884            4.9                  No         Express               No
3888            3.4                  No        Standard               No
3898            3.8                  No         Express               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
3                Yes                  49         PayPal                 Weekly
5                Yes                  14          Venmo                 Weekly
10               Yes                  26  Bank Transfer              Bi-Weekly
62               Yes                  31    Credit Card            Fortnightly
64               Yes                  18     Debit Card            Fortnightly
...              ...                 ...            ...                    ...
3873              No                  22    Credit Card                 Weekly
3876              No                   7           Cash               Annually
3884              No                   3         PayPal                 Weekly
3888              No                  14          Venmo              Bi-Weekly
3898              No                  24          Venmo                 Weekly

[599 rows x 18 columns]
-===-===-===-============------=========
Outerwear
      Customer ID  Age  Gender Item Purchased   Category  \
8               9   26    Male           Coat  Outerwear
12             13   61    Male           Coat  Outerwear
14             15   64    Male           Coat  Outerwear
24             25   18    Male         Jacket  Outerwear
32             33   36    Male         Jacket  Outerwear
...           ...  ...     ...            ...        ...
3842         3843   35  Female         Jacket  Outerwear
3861         3862   64  Female         Jacket  Outerwear
3867         3868   46  Female         Jacket  Outerwear
3869         3870   26  Female           Coat  Outerwear
3872         3873   41  Female         Jacket  Outerwear

      Purchase Amount (USD)       Location Size     Color  Season  \
8                        97  West Virginia    L    Silver  Summer
12                       72       Delaware    M      Gold  Winter
14                       53       New York    L      Teal  Winter
24                       22        Florida    M     Green    Fall
32                       67         Kansas    M    Silver  Summer
...                     ...            ...  ...       ...     ...
3842                     84       Colorado    L  Lavender  Winter
3861                     57        Wyoming    M    Yellow  Spring
3867                     21       Maryland    L  Lavender  Summer
3869                     64        Arizona    L      Cyan  Spring
3872                     94  New Hampshire    M     Green  Spring

      Review Rating Subscription Status  Shipping Type Discount Applied  \
8               2.6                 Yes        Express              Yes
12              4.5                 Yes        Express              Yes
14              4.7                 Yes  Free Shipping              Yes
24              2.9                 Yes   Store Pickup              Yes
32              4.9                 Yes  Free Shipping              Yes
...             ...                 ...            ...              ...
3842            4.2                  No   Next Day Air               No
3861            4.9                  No       Standard               No
3867            2.7                  No       Standard               No
3869            3.8                  No  Free Shipping               No
3872            4.3                  No       Standard               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
8                Yes                   8          Venmo               Annually
12               Yes                  37          Venmo            Fortnightly
14               Yes                  34     Debit Card                 Weekly
24               Yes                  16     Debit Card                 Weekly
32               Yes                  37          Venmo               Annually
...              ...                 ...            ...                    ...
3842              No                  42     Debit Card                Monthly
3861              No                  49    Credit Card                Monthly
3867              No                  28    Credit Card                Monthly
3869              No                  28  Bank Transfer               Annually
3872              No                   3           Cash                Monthly

[324 rows x 18 columns]
-===-===-===-============------=========

In [11]:
# fill nan values

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [12]:
df.isnull().sum().any()

np.False_

In [13]:
# change the column names into sneak cases

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df = df.rename(columns={"purchase_amount_(usd)" : "purchase_amount"})

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [15]:
# create a new column based on aged group

labels = ["young_adult", "adult", "middle_aged", "senior"]
df["age_group"] = pd.qcut(df["age"], q=4, labels=labels)

In [16]:
df[["age", "age_group"]]

      age    age_group
0      55  middle_aged
1      19  young_adult
2      50  middle_aged
3      21  young_adult
4      45  middle_aged
...   ...          ...
3895   40        adult
3896   52  middle_aged
3897   46  middle_aged
3898   44        adult
3899   52  middle_aged

[3900 rows x 2 columns]

In [17]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [18]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
df[['purchase_frequency_days', 'frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [20]:
df[['discount_applied', 'promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [21]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [22]:
df = df.drop('promo_code_used', axis=1)

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

## for mysql

In [24]:
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\ali\appdata\roaming\python\python312\site-packages (1.1.1)
Requirement already satisfied: sqlalchemy in c:\users\ali\appdata\roaming\python\python312\site-packages (2.0.37)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ali\appdata\roaming\python\python312\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ali\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
from sqlalchemy import create_engine

# mysql connection

username = "root"
password = "%401055"
host = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# write dataframe to MySQL

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

# read back sample
pd.read_sql("select * from customer limit 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle_aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle_aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young_adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle_aged,365